
var aidHolder='';var sidHolder='';var href='';var totalCount=0;var valueDiv='';var wwwroot='';var theme='';var userid='';var forumString='';var assignmentString='';var workshopString='';var assignmentWorkString='';var workshopWorkString='';var totalMessage='';var collapseString='';var nothingString='';var quizSaveString='';var windowobj='';var timerVar='';var frameTimerVar='';var t=0;var main='';var config='';var img='<img id="loader" src="'+wwwroot+'/lib/yui/treeview/assets/loading.gif" alt=\"loading\" />';function getVars(){wwwroot=document.getElementById('wwwrootvalue').value;if(window.location.href.match(/https:/)){wwwroot=wwwroot.replace(/http:/,"https:");}
theme=document.getElementById('themevalue').value;userid=document.getElementById('useridvalue').value;forumString=document.getElementById('forum_string').value;assignmentString=document.getElementById('assignment_string').value;workshopString=document.getElementById('workshop_string').value;assignmentWorkString=document.getElementById('assignment_work_string').value;workshopWorkString=document.getElementById('workshop_work_string').value;totalMessage=document.getElementById('total_string').value+': &nbsp;';collapseString=document.getElementById('collapse_string').value;nothingString=document.getElementById('nothing_string').value;forumSaveString=document.getElementById('forumsavestring').value;quizString=document.getElementById('quizstring').value;quizSaveString=document.getElementById('quizsavestring').value;journalString=document.getElementById('journalstring').value;journalSaveString=document.getElementById('journalsavestring').value;}
function AJAXtree(treeDiv,icon,statusDiv,config){this.config=config||null;this.loadCounter=0;var nodeHolder='';var compHolder='';this.ajaxBuild=function(){var sUrl='';if(this.loadCounter===0){this.icon.innerHTML=img;if(treeDiv=='configTree'){sUrl=wwwroot+'/blocks/ajax_marking/ajax.php?id='+userid+'&type=config_main&userid='+userid+'';}else{sUrl=wwwroot+'/blocks/ajax_marking/ajax.php?id='+userid+'&type=main&userid='+userid+'';}
var request=YAHOO.util.Connect.asyncRequest('GET',sUrl,this.ajaxCallback);this.loadCounter=1;}};var AJAXsuccess=function(o){var type=null;var responseArray=null;responseArray=eval(o.responseText);type=responseArray[0].type;responseArray.shift();switch(type){case'main':this.makeCourseNodes(responseArray);break;case'course':this.makeAssessmentNodes(responseArray);break;case'quiz_question':this.makeAssessmentNodes(responseArray);break;case'groups':this.makeGroupNodes(responseArray);break;case'submissions':this.makeSubmissionNodes(responseArray);break;case'config_main':this.makeCourseNodes(responseArray);break;case'config_course':this.makeAssessmentNodes(responseArray);break;case'config_groups':this.makeGroupsList(responseArray);break;case'config_set':if(responseArray[0].value==false){this.status.innerHTML='AJAX error';}else{this.enableRadio();}
break;case'config_check':var checkId='config'+responseArray[0].value;document.getElementById(checkId).checked=true;if(responseArray[0].value==2){responseArray.shift();this.makeGroupsList(responseArray);}
this.enableRadio();break;case'config_group_save':if(responseArray[0].value==false){this.status.innerHTML='AJAX error';}else{this.enableRadio();}
break;}};var AJAXfailure=function(o)
{if(o.tId==-1){div.innerHTML='<br />AJAX connection timed out.<br/>Click "collapse and refresh" to retry';}
if(o.tId===0){div.innerHTML='<br />AJAX connection failed.<br />Check your connection and click<br />"collapse and refresh" to retry';}};var ajaxCallback={cache:false,success:AJAXsuccess,failure:AJAXfailure,argument:1200,scope:this};this.enableRadio=function(){var h='';var radio=document.getElementById('configshowform');radio.style.color='#000';var nodes=radio.getElementsByTagName('input');for(h=0;h<nodes.length;h++){nodes[h].disabled=false;}
var groupDiv=document.getElementById('configGroups');groupDiv.style.color='#000';var groupNodes=groupDiv.getElementsByTagName('checkbox');for(h=0;h<groupNodes.length;h++){groupNodes[h].enabled=true;}}
this.disableRadio=function(){var h='';var radio=document.getElementById('configshowform');radio.style.color='#AAA';var nodes=radio.getElementsByTagName('input');for(h=0;h<nodes.length;h++){nodes[h].disabled=true;}
var groupDiv=document.getElementById('configGroups');groupDiv.style.color='#AAA';var groupNodes=groupDiv.getElementsByTagName('checkbox');for(h=0;h<groupNodes.length;h++){groupNodes[h].disabled=true;}}
var disableRadio=this.disableRadio;this.loadNodeData=function(node,onCompleteCallback){nodeHolder=node;compHolder=onCompleteCallback;var sUrl=wwwroot+'/blocks/ajax_marking/ajax.php?id='+node.data.id+'&type='+node.data.type+'&userid='+userid+'';if(typeof(node.data.gid)!='undefined'){sUrl+='&group='+node.data.gid;}
if(node.data.type=='quiz_question'){sUrl+='&quizid='+node.parent.data.id;}
var request=YAHOO.util.Connect.asyncRequest('GET',sUrl,ajaxCallback);};this.parentUpdate=function(node){var counter=node.children.length;if(counter===0){this.tree.removeNode(node,true);}else{if(node.data.type=='course'||node.children[0].data.gid!='undefined'||node.data.type=='forum'||node.data.type=='quiz'){var tempCount=0;var tempStr='';for(i=0;i<counter;i++){tempStr=node.children[i].data.count;tempCount+=parseInt(tempStr);}
countAlter(node,tempCount);}else{countAlter(node,counter);}
this.root.refresh();}};this.tooltips=function(){var name=navigator.appName;if(name!="Microsoft Internet Explorer"){var i=0;var j=0;var k=0;var m=0;var n=0;var control='';if(config===true){control=document.getElementById('config_tree_control');}else{control=document.getElementById('tree_control');}
var numberOfCourses=this.root.children.length;for(i=0;i<numberOfCourses;i++){var numberOfAssessments=this.root.children[i].children.length;for(j=0;j<numberOfAssessments;j++){node=this.root.children[i].children[j];var numberOfThirdLevelNodes=this.root.children[i].children[j].children.length;for(k=0;k<numberOfThirdLevelNodes;k++){node=this.root.children[i].children[j].children[k];check=node.data.time;if(typeof(check)!=null){this.make_tooltip(node,control)}
var numberOfFourthLevelNodes=node.children.length;for(m=0;m<numberOfFourthLevelNodes;m++){node=this.root.children[i].children[j].children[k].children[m];this.make_tooltip(node,control);var numberOfFifthLevelNodes=node.children.length;for(n=0;n<numberOfFifthLevelNodes;n++){node=this.root.children[i].children[j].children[k].children[m].children[n];this.make_tooltip(node,control);}}}}}}};this.make_tooltip=function(node,control){tempLabelEl=node.getLabelEl();tempText=node.data.summary;tempTooltip=new YAHOO.widget.Tooltip('tempTooltip',{context:tempLabelEl,text:tempText,showdelay:0,hidedelay:0,container:control,zIndex:110});}
this.makeCourseNodes=function(nodesArray){var nodesLeng=null;var label='';nodesLeng=nodesArray.length;if(nodesLeng===0){if(this.config===true){this.div.innerHTML=configNothingString;this.icon.innerHTML='';}else{this.div.innerHTML=nothingString;this.icon.innerHTML='';}}
else{var i=0;for(n=0;n<nodesLeng;n++){if(!this.config){label=nodesArray[n].name+' ('+nodesArray[n].count+')';}else{label=nodesArray[n].name;}
var myobj={label:''+label+'',id:''+nodesArray[n].id+'',type:''+nodesArray[n].type+'',count:''+nodesArray[n].count+'',cid:''+nodesArray[n].cid+'',uniqueId:''+nodesArray[n].cid+'',name:''+nodesArray[n].name+'',summary:''+nodesArray[n].summary+''};var tmpNode1=new YAHOO.widget.TextNode(myobj,this.root,false);tmpNode1.labelStyle='icon-course';tmpNode1.setDynamicLoad(this.loadNodeData);}
this.tree.draw();this.icon.innerHTML='';document.getElementById('totalmessage').innerHTML=totalMessage;this.updateTotal();}};this.makeAssessmentNodes=function(nodesArray){var myobj='';var aidHolder='';var sidHolder='';var uniqueId='';var tmpNode2='';var tmpNode3='';var clickNode='';var nodesLeng='';var label='';nodesLeng=nodesArray.length;for(m=0;m<nodesLeng;m++){switch(nodesArray[m].type){case'assignment':nodesArray[m].summary='<strong>'+assignmentString+':</strong> '+nodesArray[m].summary+'';break;case'workshop':nodesArray[m].summary='<strong>'+workshopString+':</strong> '+nodesArray[m].summary+'';break;case'forum':nodesArray[m].summary='<strong>'+forumString+':</strong> '+nodesArray[m].summary+'';break;case'quiz':nodesArray[m].summary='<strong>'+quizString+':</strong> '+nodesArray[m].summary+'';break;case'journal':nodesArray[m].summary='<strong>'+journalString+':</strong> '+nodesArray[m].summary+'';break;case'journal_submissions':nodesArray[m].summary='<strong>'+journalString+':</strong> '+nodesArray[m].summary+'';break;}
if(!this.config){label=nodesArray[m].name+' ('+nodesArray[m].count+')';}else{label=nodesArray[m].name;}
if(nodesArray[m].type=='quiz_question'){myobj={label:''+label+'',id:''+nodesArray[m].id+'',type:''+nodesArray[m].type+'',assid:''+nodesArray[m].assid+'',uniqueId:''+nodesArray[m].assid+'',count:''+nodesArray[m].count+'',name:''+nodesArray[m].name+'',summary:''+nodesArray[m].summary+'',gid:''+nodesArray[m].group+''};}else{myobj={label:''+label+'',id:''+nodesArray[m].id+'',type:''+nodesArray[m].type+'',assid:''+nodesArray[m].assid+'',uniqueId:''+nodesArray[m].assid+'',count:''+nodesArray[m].count+'',name:''+nodesArray[m].name+'',summary:''+nodesArray[m].summary+''};}
tmpNode2=new YAHOO.widget.TextNode(myobj,nodeHolder,false);switch(nodesArray[m].type){case'assignment':tmpNode2.labelStyle='icon-assign';break;case'workshop':tmpNode2.labelStyle='icon-workshop';break;case'forum':tmpNode2.labelStyle='icon-forum';break;case'quiz_question':tmpNode2.labelStyle='icon-question';break;case'quiz':tmpNode2.labelStyle='icon-quiz';break;case'journal':tmpNode2.labelStyle='icon-journal';break;}
if(this.config===true){clickNode=this.tree.getNodeByProperty('assid',nodesArray[m].assid);clickNode.onLabelClick=function(me){var title=document.getElementById('configInstructions');var check=document.getElementById('configshowform');document.getElementById('configGroups').innerHTML='';var len=check.childNodes.length;while(check.hasChildNodes()){check.removeChild(check.firstChild);}
title.innerHTML=me.data.name;check.style.color='#AAA';var hidden1=document.createElement('input');hidden1.type='hidden';hidden1.name='course';hidden1.value=me.parent.data.id;check.appendChild(hidden1);var hidden2=document.createElement('input');hidden2.type='hidden';hidden2.name='assessment';hidden2.value=me.data.id;check.appendChild(hidden2);var hidden3=document.createElement('input');hidden3.type='hidden';hidden3.name='assessmenttype';hidden3.value=me.data.type;check.appendChild(hidden3);var box1=document.createElement('input');box1.type='radio';box1.name='showhide';box1.value='show';box1.id='config1';box1.disabled=true;box1.onclick=function(){showHideChanges(this);};check.appendChild(box1);var box1text=document.createTextNode('Show');check.appendChild(box1text);var breaker=document.createElement('br');check.appendChild(breaker);var box2=document.createElement('input');box2.type='radio';box2.name='showhide';box2.value='groups';box2.id='config2';box2.disabled=true;box2.onclick=function(){showHideChanges(this);};check.appendChild(box2);var box2text=document.createTextNode('Show by group');check.appendChild(box2text);var breaker2=document.createElement('br');check.appendChild(breaker2);var box3=document.createElement('input');box3.type='radio';box3.name='showhide';box3.value='hide';box3.id='config3';box3.disabled=true;box3.onclick=function(){showHideChanges(this);};check.appendChild(box3);var box3text=document.createTextNode('Hide');check.appendChild(box3text);var checkUrl=wwwroot+'/blocks/ajax_marking/ajax.php?id='+me.parent.data.id+'&assessmenttype='+me.data.type+'&assessmentid='+me.data.id+'&userid='+userid+'&type=config_check';var request=YAHOO.util.Connect.asyncRequest('GET',checkUrl,ajaxCallback);return false;};}else if(nodesArray[m].type=='journal'){clickNode=this.tree.getNodeByProperty('assid',nodesArray[m].assid);clickNode.onLabelClick=function(me){openpopup('/mod/journal/report.php?id='+me.data.id+'',uniqueId,'menubar=0,location=0,scrollbars,resizable,width=780,height=500',0);timerVar=window.setInterval('journalOnload(\''+me.data.assid+'\', \''+me.parent.data.cid+'\')',500);return false;};}else{tmpNode2.setDynamicLoad(this.loadNodeData);}}
if(!this.config){this.parentUpdate(nodeHolder);}
compHolder();this.updateTotal();this.tooltips();};this.makeSubmissionNodes=function(nodesArray){var myobj='';var uniqueId='';var tmpNode2='';var tmpNode3='';var clickNode='';var nodesLeng='';nodesLeng=nodesArray.length;for(var k=0;k<nodesLeng;k++){uniqueId=nodesArray[k].type+nodesArray[k].aid+'sid'+nodesArray[k].sid+'';var secs=parseInt(nodesArray[k].seconds);var time=parseInt(nodesArray[k].time)*1000;var d=new Date();d.setTime(time);var nodeCount=0;if(typeof(nodesArray[k].count)!='undefined'){nodeCount=nodesArray[k].count;}
myobj={label:''+nodesArray[k].name+'',id:''+uniqueId+'',type:''+nodesArray[k].type+'',aid:''+nodesArray[k].aid+'',uniqueId:''+uniqueId+'',sid:''+nodesArray[k].sid+'',summary:''+nodesArray[k].summary+'',count:''+nodeCount+''};tmpNode3=new YAHOO.widget.TextNode(myobj,nodeHolder,false);if(secs<21600){tmpNode3.labelStyle='icon-user-one';}else if(secs<43200){tmpNode3.labelStyle='icon-user-two';}else if(secs<86400){tmpNode3.labelStyle='icon-user-three';}else if(secs<172800){tmpNode3.labelStyle='icon-user-four';}else if(secs<432000){tmpNode3.labelStyle='icon-user-five';}else if(secs<864000){tmpNode3.labelStyle='icon-user-six';}else if(secs<1209600){tmpNode3.labelStyle='icon-user-seven';}else{tmpNode3.labelStyle='icon-user-eight';}
clickNode=this.tree.getNodeByProperty('id',uniqueId);if(nodeHolder.data.type=='quiz_question'){clickNode.onLabelClick=function(me){openpopup('/mod/quiz/report.php?mode=grading&action=grade&q='+me.parent.parent.data.id+'&questionid='+me.data.aid+'&userid='+me.data.sid+'',uniqueId,'menubar=0,location=0,scrollbars,resizable,width=780,height=500',0);timerVar=window.setInterval('quizOnLoad(\''+me.data.id+'\')',500);return false;};}
else{if((nodeHolder.data.type=='assignment')||(nodeHolder.parent.data.type=='assignment')){clickNode.onLabelClick=function(me){openpopup('/mod/assignment/submissions.php?id='+me.data.aid+'&userid='
+me.data.sid+'&mode=single&offset=0','gradePopUp','menubar=0,location=0,scrollbars,resizable,width=780,height=500',0);timerVar=window.setInterval('assignmentOnLoad(\''+me.data.id+'\')',500);return false;};}
else if((nodeHolder.data.type=='workshop')||(nodeHolder.parent.data.type=='workshop')){clickNode.onLabelClick=function(me){openpopup('/mod/workshop/assess.php?id='+me.data.aid+'&sid='+me.data.sid+'&redirect='+wwwroot+'',uniqueId,'menubar=0,location=0,scrollbars,resizable,width=780,height=500',0);timerVar=window.setInterval('workshopOnLoad(\''+me.data.id+'\')',500);return false;};}
else if((nodeHolder.data.type=='forum')||(nodeHolder.parent.data.type=='forum')){clickNode.onLabelClick=function(me){openpopup('/mod/forum/discuss.php?d='+me.data.aid+'#p'+me.data.sid+'',uniqueId,'menubar=0,location=0,scrollbars,resizable,width=780,height=500',0);timerVar=window.setInterval('forumOnLoad(\''+me.data.id+'\')',500);return false;};}}}
this.parentUpdate(nodeHolder);this.parentUpdate(nodeHolder.parent);if(!nodeHolder.parent.parent.isRoot()){this.parentUpdate(nodeHolder.parent.parent);if(!nodeHolder.parent.parent.parent.isRoot()){this.parentUpdate(nodeHolder.parent.parent.parent);}}
compHolder();this.updateTotal();this.tooltips();};this.makeGroupNodes=function(responseArray){var object='';var arrayLength=responseArray.length;var tmpNode4='';var label='';for(var n=0;n<arrayLength;n++){uniqueId='group'+responseArray[n].gid+'';label=responseArray[n].name+' ('+responseArray[n].count+')';object={label:''+label+'',name:''+responseArray[n].name+'',id:''+responseArray[n].aid+'',type:''+responseArray[n].type+'',uniqueId:''+'g'+responseArray[n].gid+responseArray[n].type+responseArray[n].aid+'',gid:''+responseArray[n].gid+'',count:''+responseArray[n].count+'',summary:''+responseArray[n].summary+''};tmpNode4=new YAHOO.widget.TextNode(object,nodeHolder,false);tmpNode4.labelStyle='icon-group';if(responseArray[n].type=='journal'){clickNode=this.tree.getNodeByProperty('assid',nodesArray[m].assid);clickNode.onLabelClick=function(me){openpopup('/mod/journal/report.php?id='+me.data.id+'&group='+me.data.gid+'',uniqueId,'menubar=0,location=0,scrollbars,resizable,width=780,height=500',0);timerVar=window.setInterval('journalOnload(\''+me.data.assid+'\', \''+me.parent.data.cid+'\')',500);return false;};}else{tmpNode4.setDynamicLoad(this.loadNodeData);}}
this.parentUpdate(nodeHolder);this.parentUpdate(nodeHolder.parent);compHolder();this.updateTotal();this.tooltips();};this.refreshRoot=function(){this.root.refresh();if(this.root.children.length===0){document.getElementById("totalmessage").innerHTML='';document.getElementById("count").innerHTML='';this.div.innerHTML+=nothingString;}};this.refreshRootFrames=function(){this.root.refresh();if(this.root.children.length===0){document.getElementById("totalmessage").innerHTML='';document.getElementById("count").innerHTML='';this.div.innerHTML+=nothingString;}};this.updateTotal=function(){var count=0;var countTemp=0;var childrenLength=this.root.children;for(i=0;i<childrenLength.length;i++){countTemp=childrenLength[i].data.count;count=count+parseInt(countTemp);}
if(count>0){document.getElementById('count').innerHTML='<strong>'+count+'</strong>';}};this.saveChangesAJAX=function(thisNodeId,frames){var checkNode="";var parentNode="";var marker=0;checkNode=this.tree.getNodeByProperty("id",thisNodeId);parentNode=this.tree.getNodeByIndex(checkNode.parent.index);this.tree.removeNode(checkNode,true);while(marker==0){this.parentUpdate(parentNode);if(parentNode.data.type=='assessments'){marker=1;}else{newNode=this.tree.getNodeByIndex(parentNode.parent.index);parentNode=newNode;}}
if(typeof(frames)!='undefined'){this.refreshRootFrames();}else{this.refreshRoot();}
this.updateTotal();this.tooltips();};this.refreshTree=function(){this.loadCounter=0;delete this.tree;this.root='';this.div.innerHTML='';this.treeDiv.innerHTML='';this.make_tree();};this.makeGroupsList=function(data){var groupDiv=document.getElementById('configGroups');var dataLength=data.length;var idCounter=4;for(var v=0;v<dataLength;v++){var box=document.createElement('input');box.type='checkbox';box.id='config'+idCounter;box.name='groups';box.value=data[v].id;if(data[v].display=='true'){box.checked=true;}else{box.checked=false;}
groupDiv.appendChild(box);box.onclick=function(){var form=document.getElementById('configshowform');disableRadio();var groupIds='';var groupDiv=document.getElementById('configGroups');var groups=groupDiv.getElementsByTagName('input');var groupsLength=groups.length;for(var a=0;a<groupsLength;a++){if(groups[a].checked==true){groupIds+=groups[a].value+' ';}}
if(groupIds==''){groupIds='none';}
var reqUrl=wwwroot+'/blocks/ajax_marking/ajax.php?id='+form.course.value+'&assessmenttype='+form.assessmenttype.value+'&assessmentid='+form.assessment.value+'&type=config_group_save&userid='+userid+'&showhide=2&groups='+groupIds+'';var request=YAHOO.util.Connect.asyncRequest('GET',reqUrl,ajaxCallback);}
var label=document.createTextNode(data[v].name);groupDiv.appendChild(label);var breaker=document.createElement('br');groupDiv.appendChild(breaker);idCounter++;}
this.icon.innerHTML='';this.enableRadio();};this.ajaxCallback=ajaxCallback;this.make_tree=function(){YAHOO.widget.TreeView.preload();var tree=new YAHOO.widget.TreeView(treeDiv);this.tree=tree;this.div=document.getElementById(statusDiv);this.treeDiv=treeDiv;this.icon=document.getElementById(icon);this.tree.subscribe('collapseComplete',function(node){tree.removeChildren(node);});this.root=this.tree.getRoot();this.ajaxBuild();}
this.make_tree();}
function countAlter(newNode,newCount){var name=newNode.data.name;var newLabel=name+' ('+newCount+')';newNode.data.count=newCount;newNode.label=newLabel;}
function assignmentOnLoad(me,parent,course){var els='';var els2='';var els3='';t=t+1;if(typeof(windowobj.document.getElementsByName('submit'))!='undefined'){els=windowobj.document.getElementsByName('submit');if(els.length!==0){var name=navigator.appName;if(name=="Microsoft Internet Explorer"){els[0]["onclick"]=new Function("windowobj.document.getElementById('submitform').menuindex.value = windowobj.document.getElementById('submitform').grade.selectedIndex; main.saveChangesAJAX('"+me+"', '"+parent+"', '"+course+"'); ");}else{els[0].setAttribute("onClick","document.getElementById('submitform').menuindex.value = document.getElementById('submitform').grade.selectedIndex; return window.opener.main.saveChangesAJAX('"+me+"', '"+parent+"', '"+course+"')");}
if(typeof(windowobj.document.getElementsByName('saveandnext'))!='undefined'){els2=windowobj.document.getElementsByName('saveandnext');if(els2.length!==0){els2[0].style.display="none";els3=windowobj.document.getElementsByName('next');els3[0].style.display="none";}}
timerVar=window.clearInterval(timerVar);}}}
function workshopOnLoad(me,parent,course){var els='';if(typeof(windowobj.frames[0])!='undefined'){if(windowobj.frames[0].location.href!=wwwroot+'/mod/workshop/assessments.php'){els=windowobj.frames[0].document.getElementsByTagName('input');if(els.length==11){els[10]["onclick"]=new Function("saveChangesAJAX('"+me+"', true);");timerVar=window.clearInterval(timerVar);timerVar=self.setInterval('afterLoad("/mod/workshop/assessments.php")',500);}}}}
function forumOnLoad(me){var els='';var name=navigator.appName;if(typeof(windowobj.document.getElementsByTagName('input'))!='undefined'){els=windowobj.document.getElementsByTagName('input');if(els.length>0){var key=els.length-1;if(els[key].value==forumSaveString){if(name!="Microsoft Internet Explorer"){els[key].setAttribute("onClick","return saveChangesAJAX('"+me+"')");}else{els[key]["onclick"]=new Function("return saveChangesAJAX('"+me+"');");}
timerVar=window.clearInterval(timerVar);timerVar=self.setInterval('afterLoad("/mod/forum/rate.php")',500);}}}}
function quizOnLoad(me){var els='';var lastButOne='';t=t+1;if(typeof(windowobj.document.getElementsByTagName('input'))!='undefined'){els=windowobj.document.getElementsByTagName('input');if(els.length>14){lastButOne=els.length-1;if(els[lastButOne].value==quizSaveString){var name=navigator.appName;if(name=="Microsoft Internet Explorer"){els[lastButOne]["onclick"]=new Function("saveChangesAJAX('"+me+"'); ");}else{els[lastButOne].setAttribute("onClick","window.opener.saveChangesAJAX('"+me+"')");}
timerVar=window.clearInterval(timerVar);timerVar=self.setInterval('afterLoad("/mod/quiz/report.php")',500);}}}}
function journalOnLoad(me){var els='';if(typeof(windowobj.document.getElementsByTagName('input'))!='undefined'){els=windowobj.document.getElementsByTagName('input');if(els.length>0){var key=els.length-1;if(els[key].value==journalSaveString){els[key].setAttribute("onClick","return saveChangesAJAX('"+me+"')");els[key]["onclick"]=new Function("return saveChangesAJAX('"+me+"');");timerVar=window.clearInterval(timerVar);timerVar=self.setInterval('afterLoad("/mod/journal/report.php")',500);}}}}
function afterLoad(loc){if(windowobj.closed){timerVar=window.clearInterval(timerVar);}
if(!windowobj.closed&&windowobj.location.href==wwwroot+loc){setTimeout('windowobj.close()',1000);timerVar=window.clearInterval(timerVar);}}
function grayOut(vis,options){if(!options){options='';}
var zindex=options.zindex||50;var opacity=options.opacity||70;var opaque=(opacity/100);var bgcolor=options.bgcolor||'#000000';var dark=document.getElementById('darkenScreenObject');var dialog=document.getElementById('dialog');var windowHeight=alertSize();var pageHeight='';var pageWidth='';var screenWidth='';if(!dark){var tbody=document.getElementsByTagName("body")[0];var tnode=document.createElement('div');tnode.style.position='absolute';tnode.style.top='0px';tnode.style.left='0px';tnode.style.overflow='hidden';tnode.style.display='none';tnode.id='darkenScreenObject';tbody.appendChild(tnode);dark=document.getElementById('darkenScreenObject');}
if(vis){if(document.body&&(document.body.scrollWidth||document.body.scrollHeight)){pageWidth=document.body.scrollWidth+'px';screenWidth=document.body.scrollWidth;if(document.body.scrollHeight<windowHeight){pageHeight=windowHeight+'px';}else{pageHeight=document.body.scrollHeight+'px';}}else if(document.body.offsetWidth){pageWidth=document.body.offsetWidth+'px';screenWidth=document.body.offsetWidth;if(document.body.offsetHeight<windowHeight){pageHeight=windowHeight+'px';}else{pageHeight=document.body.offsetHeight+'px';}}else{screenWidth=800;pageWidth='100%';pageHeight='100%';}
var y=0;if(self.pageYOffset)
{y=window.scrollY;dialog.style.top=(y-100)+'px';}
else if(document.documentElement&&document.documentElement.scrollTop)
{y=document.documentElement.scrollTop;}
else if(document.body)
{y=document.body.scrollTop;}
dark.style.opacity=opaque;dark.style.MozOpacity=opaque;dark.style.filter='alpha(opacity='+opacity+')';dark.style.zIndex=zindex;dark.style.backgroundColor=bgcolor;dark.style.width=pageWidth;dark.style.height=pageHeight;dark.style.display='block';dialog.style.right=((screenWidth-400)/2)+'px';dialog.style.top=(y-100)+'px';dialog.style.height=screen.availHeight-300+'px';dialog.style.display='block';document.getElementById('configshowform').innerHTML='';document.getElementById('configTree').innerHTML='';document.getElementById('configInstructions').innerHTML='';config=new AJAXtree('configTree','configIcon','configStatus',true);config.icon=document.getElementById('configIcon');}else{document.getElementById("configGroups").innerHTML="";dark.style.display='none';dialog.style.display='none';}}
function alertSize(){var myHeight=0;if(typeof(window.innerWidth)=='number'){myHeight=window.innerHeight;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){myHeight=document.documentElement.clientHeight;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){myHeight=document.body.clientHeight;}
return myHeight;}
function showHideChanges(checkbox){var showHide='';config.disableRadio();switch(checkbox.value){case'groups':showHide=2;var form=document.getElementById('configshowform');var url=wwwroot+'/blocks/ajax_marking/ajax.php?id='+form.course.value+'&assessmenttype='+form.assessmenttype.value+'&assessmentid='+form.assessment.value+'&type=config_groups&userid='+userid+'&showhide='+showHide+'';var request=YAHOO.util.Connect.asyncRequest('GET',url,config.ajaxCallback);break;case'show':document.getElementById('configGroups').innerHTML='';configSet(1);break;case'hide':document.getElementById('configGroups').innerHTML='';configSet(3);break;}}
function configSet(showHide){var form=document.getElementById('configshowform');var url=wwwroot+'/blocks/ajax_marking/ajax.php?id='+form.assessment.value+'&type=config_set&userid='+userid+'&assessmenttype='+form.assessmenttype.value+'&assessmentid='+form.assessment.value+'&showhide='+showHide+'';var request=YAHOO.util.Connect.asyncRequest('GET',url,config.ajaxCallback);}
function init(){getVars();main=new AJAXtree('treediv','mainIcon','status');}
YAHOO.util.Event.onDOMReady(init);